// Defines the message contract for the LLM service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: src/types/builder/v1/builder.proto

package builder_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shared wire format for both inline attachments and data source pointers
type NetworkAttachmentPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DataSourceId  string                 `protobuf:"bytes,2,opt,name=data_source_id,json=dataSourceId,proto3" json:"data_source_id,omitempty"`
	ProfileId     *string                `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAttachmentPb) Reset() {
	*x = NetworkAttachmentPb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAttachmentPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAttachmentPb) ProtoMessage() {}

func (x *NetworkAttachmentPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAttachmentPb.ProtoReflect.Descriptor instead.
func (*NetworkAttachmentPb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkAttachmentPb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkAttachmentPb) GetDataSourceId() string {
	if x != nil {
		return x.DataSourceId
	}
	return ""
}

func (x *NetworkAttachmentPb) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

type BuildCacheRequestPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Sources       []*NetworkAttachmentPb `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	ExpiresAtHint *string                `protobuf:"bytes,3,opt,name=expires_at_hint,json=expiresAtHint,proto3,oneof" json:"expires_at_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildCacheRequestPb) Reset() {
	*x = BuildCacheRequestPb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCacheRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCacheRequestPb) ProtoMessage() {}

func (x *BuildCacheRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCacheRequestPb.ProtoReflect.Descriptor instead.
func (*BuildCacheRequestPb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{1}
}

func (x *BuildCacheRequestPb) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *BuildCacheRequestPb) GetSources() []*NetworkAttachmentPb {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *BuildCacheRequestPb) GetExpiresAtHint() string {
	if x != nil && x.ExpiresAtHint != nil {
		return *x.ExpiresAtHint
	}
	return ""
}

type BuildCacheResponsePb struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CompiledCacheId string                 `protobuf:"bytes,1,opt,name=compiled_cache_id,json=compiledCacheId,proto3" json:"compiled_cache_id,omitempty"`
	ExpiresAt       string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BuildCacheResponsePb) Reset() {
	*x = BuildCacheResponsePb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCacheResponsePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCacheResponsePb) ProtoMessage() {}

func (x *BuildCacheResponsePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCacheResponsePb.ProtoReflect.Descriptor instead.
func (*BuildCacheResponsePb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{2}
}

func (x *BuildCacheResponsePb) GetCompiledCacheId() string {
	if x != nil {
		return x.CompiledCacheId
	}
	return ""
}

func (x *BuildCacheResponsePb) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type GenerateRequestPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequestPb) Reset() {
	*x = GenerateRequestPb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequestPb) ProtoMessage() {}

func (x *GenerateRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequestPb.ProtoReflect.Descriptor instead.
func (*GenerateRequestPb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateRequestPb) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateRequestPb) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *GenerateRequestPb) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GenerateResponsePb struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Content             string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FinishReason        string                 `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	PromptTokenCount    int32                  `protobuf:"varint,3,opt,name=prompt_token_count,json=promptTokenCount,proto3" json:"prompt_token_count,omitempty"`
	CandidateTokenCount int32                  `protobuf:"varint,4,opt,name=candidate_token_count,json=candidateTokenCount,proto3" json:"candidate_token_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GenerateResponsePb) Reset() {
	*x = GenerateResponsePb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponsePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponsePb) ProtoMessage() {}

func (x *GenerateResponsePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponsePb.ProtoReflect.Descriptor instead.
func (*GenerateResponsePb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateResponsePb) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GenerateResponsePb) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *GenerateResponsePb) GetPromptTokenCount() int32 {
	if x != nil {
		return x.PromptTokenCount
	}
	return 0
}

func (x *GenerateResponsePb) GetCandidateTokenCount() int32 {
	if x != nil {
		return x.CandidateTokenCount
	}
	return 0
}

type NetworkMessagePb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMessagePb) Reset() {
	*x = NetworkMessagePb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMessagePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMessagePb) ProtoMessage() {}

func (x *NetworkMessagePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMessagePb.ProtoReflect.Descriptor instead.
func (*NetworkMessagePb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkMessagePb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkMessagePb) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NetworkMessagePb) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NetworkMessagePb) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GenerateStreamRequestPb struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Model             string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	History           []*NetworkMessagePb    `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	CompiledCacheId   *string                `protobuf:"bytes,4,opt,name=compiled_cache_id,json=compiledCacheId,proto3,oneof" json:"compiled_cache_id,omitempty"`
	InlineAttachments []*NetworkAttachmentPb `protobuf:"bytes,5,rep,name=inline_attachments,json=inlineAttachments,proto3" json:"inline_attachments,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateStreamRequestPb) Reset() {
	*x = GenerateStreamRequestPb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStreamRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStreamRequestPb) ProtoMessage() {}

func (x *GenerateStreamRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStreamRequestPb.ProtoReflect.Descriptor instead.
func (*GenerateStreamRequestPb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateStreamRequestPb) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GenerateStreamRequestPb) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateStreamRequestPb) GetHistory() []*NetworkMessagePb {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GenerateStreamRequestPb) GetCompiledCacheId() string {
	if x != nil && x.CompiledCacheId != nil {
		return *x.CompiledCacheId
	}
	return ""
}

func (x *GenerateStreamRequestPb) GetInlineAttachments() []*NetworkAttachmentPb {
	if x != nil {
		return x.InlineAttachments
	}
	return nil
}

type FileStatePb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,2,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatePb) Reset() {
	*x = FileStatePb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatePb) ProtoMessage() {}

func (x *FileStatePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatePb.ProtoReflect.Descriptor instead.
func (*FileStatePb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{7}
}

func (x *FileStatePb) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileStatePb) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type ChangeProposalPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Patch         *string                `protobuf:"bytes,3,opt,name=patch,proto3,oneof" json:"patch,omitempty"`
	NewContent    *string                `protobuf:"bytes,4,opt,name=new_content,json=newContent,proto3,oneof" json:"new_content,omitempty"`
	Reasoning     string                 `protobuf:"bytes,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeProposalPb) Reset() {
	*x = ChangeProposalPb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeProposalPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeProposalPb) ProtoMessage() {}

func (x *ChangeProposalPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeProposalPb.ProtoReflect.Descriptor instead.
func (*ChangeProposalPb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{8}
}

func (x *ChangeProposalPb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeProposalPb) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ChangeProposalPb) GetPatch() string {
	if x != nil && x.Patch != nil {
		return *x.Patch
	}
	return ""
}

func (x *ChangeProposalPb) GetNewContent() string {
	if x != nil && x.NewContent != nil {
		return *x.NewContent
	}
	return ""
}

func (x *ChangeProposalPb) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ChangeProposalPb) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChangeProposalPb) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CompiledCachePb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Sources       []*NetworkAttachmentPb `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompiledCachePb) Reset() {
	*x = CompiledCachePb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledCachePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledCachePb) ProtoMessage() {}

func (x *CompiledCachePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledCachePb.ProtoReflect.Descriptor instead.
func (*CompiledCachePb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{9}
}

func (x *CompiledCachePb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompiledCachePb) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CompiledCachePb) GetSources() []*NetworkAttachmentPb {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *CompiledCachePb) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CompiledCachePb) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type SessionPb struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompiledCacheId string                 `protobuf:"bytes,2,opt,name=compiled_cache_id,json=compiledCacheId,proto3" json:"compiled_cache_id,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SessionPb) Reset() {
	*x = SessionPb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPb) ProtoMessage() {}

func (x *SessionPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPb.ProtoReflect.Descriptor instead.
func (*SessionPb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{10}
}

func (x *SessionPb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionPb) GetCompiledCacheId() string {
	if x != nil {
		return x.CompiledCacheId
	}
	return ""
}

func (x *SessionPb) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_src_types_builder_v1_builder_proto protoreflect.FileDescriptor

const file_src_types_builder_v1_builder_proto_rawDesc = "" +
	"\n" +
	"\"src/types/builder/v1/builder.proto\x12\x14src.types.builder.v1\"~\n" +
	"\x13NetworkAttachmentPb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0edata_source_id\x18\x02 \x01(\tR\fdataSourceId\x12\"\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tH\x00R\tprofileId\x88\x01\x01B\r\n" +
	"\v_profile_id\"\xb1\x01\n" +
	"\x13BuildCacheRequestPb\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12C\n" +
	"\asources\x18\x02 \x03(\v2).src.types.builder.v1.NetworkAttachmentPbR\asources\x12+\n" +
	"\x0fexpires_at_hint\x18\x03 \x01(\tH\x00R\rexpiresAtHint\x88\x01\x01B\x12\n" +
	"\x10_expires_at_hint\"a\n" +
	"\x14BuildCacheResponsePb\x12*\n" +
	"\x11compiled_cache_id\x18\x01 \x01(\tR\x0fcompiledCacheId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\"f\n" +
	"\x11GenerateRequestPb\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\"\xb5\x01\n" +
	"\x12GenerateResponsePb\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\x12,\n" +
	"\x12prompt_token_count\x18\x03 \x01(\x05R\x10promptTokenCount\x122\n" +
	"\x15candidate_token_count\x18\x04 \x01(\x05R\x13candidateTokenCount\"n\n" +
	"\x10NetworkMessagePb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xb1\x02\n" +
	"\x17GenerateStreamRequestPb\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12@\n" +
	"\ahistory\x18\x03 \x03(\v2&.src.types.builder.v1.NetworkMessagePbR\ahistory\x12/\n" +
	"\x11compiled_cache_id\x18\x04 \x01(\tH\x00R\x0fcompiledCacheId\x88\x01\x01\x12X\n" +
	"\x12inline_attachments\x18\x05 \x03(\v2).src.types.builder.v1.NetworkAttachmentPbR\x11inlineAttachmentsB\x14\n" +
	"\x12_compiled_cache_id\"F\n" +
	"\vFileStatePb\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x02 \x01(\bR\tisDeleted\"\xf6\x01\n" +
	"\x10ChangeProposalPb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12\x19\n" +
	"\x05patch\x18\x03 \x01(\tH\x00R\x05patch\x88\x01\x01\x12$\n" +
	"\vnew_content\x18\x04 \x01(\tH\x01R\n" +
	"newContent\x88\x01\x01\x12\x1c\n" +
	"\treasoning\x18\x05 \x01(\tR\treasoning\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionIdB\b\n" +
	"\x06_patchB\x0e\n" +
	"\f_new_content\"\xc0\x01\n" +
	"\x0fCompiledCachePb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12C\n" +
	"\asources\x18\x03 \x03(\v2).src.types.builder.v1.NetworkAttachmentPbR\asources\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\tR\texpiresAt\"f\n" +
	"\tSessionPb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11compiled_cache_id\x18\x02 \x01(\tR\x0fcompiledCacheId\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAtBBZ@github.com/tinywideclouds/gen-llm/go/types/builder/v1;builder_v1b\x06proto3"

var (
	file_src_types_builder_v1_builder_proto_rawDescOnce sync.Once
	file_src_types_builder_v1_builder_proto_rawDescData []byte
)

func file_src_types_builder_v1_builder_proto_rawDescGZIP() []byte {
	file_src_types_builder_v1_builder_proto_rawDescOnce.Do(func() {
		file_src_types_builder_v1_builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_types_builder_v1_builder_proto_rawDesc), len(file_src_types_builder_v1_builder_proto_rawDesc)))
	})
	return file_src_types_builder_v1_builder_proto_rawDescData
}

var file_src_types_builder_v1_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_src_types_builder_v1_builder_proto_goTypes = []any{
	(*NetworkAttachmentPb)(nil),     // 0: src.types.builder.v1.NetworkAttachmentPb
	(*BuildCacheRequestPb)(nil),     // 1: src.types.builder.v1.BuildCacheRequestPb
	(*BuildCacheResponsePb)(nil),    // 2: src.types.builder.v1.BuildCacheResponsePb
	(*GenerateRequestPb)(nil),       // 3: src.types.builder.v1.GenerateRequestPb
	(*GenerateResponsePb)(nil),      // 4: src.types.builder.v1.GenerateResponsePb
	(*NetworkMessagePb)(nil),        // 5: src.types.builder.v1.NetworkMessagePb
	(*GenerateStreamRequestPb)(nil), // 6: src.types.builder.v1.GenerateStreamRequestPb
	(*FileStatePb)(nil),             // 7: src.types.builder.v1.FileStatePb
	(*ChangeProposalPb)(nil),        // 8: src.types.builder.v1.ChangeProposalPb
	(*CompiledCachePb)(nil),         // 9: src.types.builder.v1.CompiledCachePb
	(*SessionPb)(nil),               // 10: src.types.builder.v1.SessionPb
}
var file_src_types_builder_v1_builder_proto_depIdxs = []int32{
	0, // 0: src.types.builder.v1.BuildCacheRequestPb.sources:type_name -> src.types.builder.v1.NetworkAttachmentPb
	5, // 1: src.types.builder.v1.GenerateStreamRequestPb.history:type_name -> src.types.builder.v1.NetworkMessagePb
	0, // 2: src.types.builder.v1.GenerateStreamRequestPb.inline_attachments:type_name -> src.types.builder.v1.NetworkAttachmentPb
	0, // 3: src.types.builder.v1.CompiledCachePb.sources:type_name -> src.types.builder.v1.NetworkAttachmentPb
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_src_types_builder_v1_builder_proto_init() }
func file_src_types_builder_v1_builder_proto_init() {
	if File_src_types_builder_v1_builder_proto != nil {
		return
	}
	file_src_types_builder_v1_builder_proto_msgTypes[0].OneofWrappers = []any{}
	file_src_types_builder_v1_builder_proto_msgTypes[1].OneofWrappers = []any{}
	file_src_types_builder_v1_builder_proto_msgTypes[6].OneofWrappers = []any{}
	file_src_types_builder_v1_builder_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_types_builder_v1_builder_proto_rawDesc), len(file_src_types_builder_v1_builder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_types_builder_v1_builder_proto_goTypes,
		DependencyIndexes: file_src_types_builder_v1_builder_proto_depIdxs,
		MessageInfos:      file_src_types_builder_v1_builder_proto_msgTypes,
	}.Build()
	File_src_types_builder_v1_builder_proto = out.File
	file_src_types_builder_v1_builder_proto_goTypes = nil
	file_src_types_builder_v1_builder_proto_depIdxs = nil
}
