// Defines the message contract for the LLM service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: src/types/builder/v1/builder.proto

package builder_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NetworkAttachmentPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CacheId       string                 `protobuf:"bytes,2,opt,name=cache_id,json=cacheId,proto3" json:"cache_id,omitempty"`
	ProfileId     *string                `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3,oneof" json:"profile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAttachmentPb) Reset() {
	*x = NetworkAttachmentPb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAttachmentPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAttachmentPb) ProtoMessage() {}

func (x *NetworkAttachmentPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAttachmentPb.ProtoReflect.Descriptor instead.
func (*NetworkAttachmentPb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkAttachmentPb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkAttachmentPb) GetCacheId() string {
	if x != nil {
		return x.CacheId
	}
	return ""
}

func (x *NetworkAttachmentPb) GetProfileId() string {
	if x != nil && x.ProfileId != nil {
		return *x.ProfileId
	}
	return ""
}

type BuildCacheRequestPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Attachments   []*NetworkAttachmentPb `protobuf:"bytes,3,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildCacheRequestPb) Reset() {
	*x = BuildCacheRequestPb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCacheRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCacheRequestPb) ProtoMessage() {}

func (x *BuildCacheRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCacheRequestPb.ProtoReflect.Descriptor instead.
func (*BuildCacheRequestPb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{1}
}

func (x *BuildCacheRequestPb) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BuildCacheRequestPb) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *BuildCacheRequestPb) GetAttachments() []*NetworkAttachmentPb {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type BuildCacheResponsePb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeminiCacheId string                 `protobuf:"bytes,1,opt,name=gemini_cache_id,json=geminiCacheId,proto3" json:"gemini_cache_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildCacheResponsePb) Reset() {
	*x = BuildCacheResponsePb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCacheResponsePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCacheResponsePb) ProtoMessage() {}

func (x *BuildCacheResponsePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCacheResponsePb.ProtoReflect.Descriptor instead.
func (*BuildCacheResponsePb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{2}
}

func (x *BuildCacheResponsePb) GetGeminiCacheId() string {
	if x != nil {
		return x.GeminiCacheId
	}
	return ""
}

type NetworkMessagePb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMessagePb) Reset() {
	*x = NetworkMessagePb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMessagePb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMessagePb) ProtoMessage() {}

func (x *NetworkMessagePb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMessagePb.ProtoReflect.Descriptor instead.
func (*NetworkMessagePb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkMessagePb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkMessagePb) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NetworkMessagePb) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NetworkMessagePb) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type GenerateStreamRequestPb struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Model             string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	History           []*NetworkMessagePb    `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	GeminiCacheId     *string                `protobuf:"bytes,4,opt,name=gemini_cache_id,json=geminiCacheId,proto3,oneof" json:"gemini_cache_id,omitempty"`
	InlineAttachments []*NetworkAttachmentPb `protobuf:"bytes,5,rep,name=inline_attachments,json=inlineAttachments,proto3" json:"inline_attachments,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateStreamRequestPb) Reset() {
	*x = GenerateStreamRequestPb{}
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateStreamRequestPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateStreamRequestPb) ProtoMessage() {}

func (x *GenerateStreamRequestPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_builder_v1_builder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateStreamRequestPb.ProtoReflect.Descriptor instead.
func (*GenerateStreamRequestPb) Descriptor() ([]byte, []int) {
	return file_src_types_builder_v1_builder_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateStreamRequestPb) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GenerateStreamRequestPb) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateStreamRequestPb) GetHistory() []*NetworkMessagePb {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GenerateStreamRequestPb) GetGeminiCacheId() string {
	if x != nil && x.GeminiCacheId != nil {
		return *x.GeminiCacheId
	}
	return ""
}

func (x *GenerateStreamRequestPb) GetInlineAttachments() []*NetworkAttachmentPb {
	if x != nil {
		return x.InlineAttachments
	}
	return nil
}

var File_src_types_builder_v1_builder_proto protoreflect.FileDescriptor

const file_src_types_builder_v1_builder_proto_rawDesc = "" +
	"\n" +
	"\"src/types/builder/v1/builder.proto\x12\x14src.types.builder.v1\"s\n" +
	"\x13NetworkAttachmentPb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bcache_id\x18\x02 \x01(\tR\acacheId\x12\"\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tH\x00R\tprofileId\x88\x01\x01B\r\n" +
	"\v_profile_id\"\x97\x01\n" +
	"\x13BuildCacheRequestPb\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12K\n" +
	"\vattachments\x18\x03 \x03(\v2).src.types.builder.v1.NetworkAttachmentPbR\vattachments\">\n" +
	"\x14BuildCacheResponsePb\x12&\n" +
	"\x0fgemini_cache_id\x18\x01 \x01(\tR\rgeminiCacheId\"n\n" +
	"\x10NetworkMessagePb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xab\x02\n" +
	"\x17GenerateStreamRequestPb\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12@\n" +
	"\ahistory\x18\x03 \x03(\v2&.src.types.builder.v1.NetworkMessagePbR\ahistory\x12+\n" +
	"\x0fgemini_cache_id\x18\x04 \x01(\tH\x00R\rgeminiCacheId\x88\x01\x01\x12X\n" +
	"\x12inline_attachments\x18\x05 \x03(\v2).src.types.builder.v1.NetworkAttachmentPbR\x11inlineAttachmentsB\x12\n" +
	"\x10_gemini_cache_idBBZ@github.com/tinywideclouds/gen-llm/go/types/builder/v1;builder_v1b\x06proto3"

var (
	file_src_types_builder_v1_builder_proto_rawDescOnce sync.Once
	file_src_types_builder_v1_builder_proto_rawDescData []byte
)

func file_src_types_builder_v1_builder_proto_rawDescGZIP() []byte {
	file_src_types_builder_v1_builder_proto_rawDescOnce.Do(func() {
		file_src_types_builder_v1_builder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_types_builder_v1_builder_proto_rawDesc), len(file_src_types_builder_v1_builder_proto_rawDesc)))
	})
	return file_src_types_builder_v1_builder_proto_rawDescData
}

var file_src_types_builder_v1_builder_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_types_builder_v1_builder_proto_goTypes = []any{
	(*NetworkAttachmentPb)(nil),     // 0: src.types.builder.v1.NetworkAttachmentPb
	(*BuildCacheRequestPb)(nil),     // 1: src.types.builder.v1.BuildCacheRequestPb
	(*BuildCacheResponsePb)(nil),    // 2: src.types.builder.v1.BuildCacheResponsePb
	(*NetworkMessagePb)(nil),        // 3: src.types.builder.v1.NetworkMessagePb
	(*GenerateStreamRequestPb)(nil), // 4: src.types.builder.v1.GenerateStreamRequestPb
}
var file_src_types_builder_v1_builder_proto_depIdxs = []int32{
	0, // 0: src.types.builder.v1.BuildCacheRequestPb.attachments:type_name -> src.types.builder.v1.NetworkAttachmentPb
	3, // 1: src.types.builder.v1.GenerateStreamRequestPb.history:type_name -> src.types.builder.v1.NetworkMessagePb
	0, // 2: src.types.builder.v1.GenerateStreamRequestPb.inline_attachments:type_name -> src.types.builder.v1.NetworkAttachmentPb
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_src_types_builder_v1_builder_proto_init() }
func file_src_types_builder_v1_builder_proto_init() {
	if File_src_types_builder_v1_builder_proto != nil {
		return
	}
	file_src_types_builder_v1_builder_proto_msgTypes[0].OneofWrappers = []any{}
	file_src_types_builder_v1_builder_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_types_builder_v1_builder_proto_rawDesc), len(file_src_types_builder_v1_builder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_types_builder_v1_builder_proto_goTypes,
		DependencyIndexes: file_src_types_builder_v1_builder_proto_depIdxs,
		MessageInfos:      file_src_types_builder_v1_builder_proto_msgTypes,
	}.Build()
	File_src_types_builder_v1_builder_proto = out.File
	file_src_types_builder_v1_builder_proto_goTypes = nil
	file_src_types_builder_v1_builder_proto_depIdxs = nil
}
