// Defines the message contract for the LLM service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: src/types/cache/v1/cache.proto

package cache_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreCollectionsPb struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BundleCollection   string                 `protobuf:"bytes,1,opt,name=bundle_collection,json=bundleCollection,proto3" json:"bundle_collection,omitempty"`
	FilesCollection    string                 `protobuf:"bytes,2,opt,name=files_collection,json=filesCollection,proto3" json:"files_collection,omitempty"`
	ProfilesCollection string                 `protobuf:"bytes,3,opt,name=profiles_collection,json=profilesCollection,proto3" json:"profiles_collection,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StoreCollectionsPb) Reset() {
	*x = StoreCollectionsPb{}
	mi := &file_src_types_cache_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreCollectionsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreCollectionsPb) ProtoMessage() {}

func (x *StoreCollectionsPb) ProtoReflect() protoreflect.Message {
	mi := &file_src_types_cache_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreCollectionsPb.ProtoReflect.Descriptor instead.
func (*StoreCollectionsPb) Descriptor() ([]byte, []int) {
	return file_src_types_cache_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *StoreCollectionsPb) GetBundleCollection() string {
	if x != nil {
		return x.BundleCollection
	}
	return ""
}

func (x *StoreCollectionsPb) GetFilesCollection() string {
	if x != nil {
		return x.FilesCollection
	}
	return ""
}

func (x *StoreCollectionsPb) GetProfilesCollection() string {
	if x != nil {
		return x.ProfilesCollection
	}
	return ""
}

var File_src_types_cache_v1_cache_proto protoreflect.FileDescriptor

const file_src_types_cache_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x1esrc/types/cache/v1/cache.proto\x12\x12src.types.cache.v1\"\x9d\x01\n" +
	"\x12StoreCollectionsPb\x12+\n" +
	"\x11bundle_collection\x18\x01 \x01(\tR\x10bundleCollection\x12)\n" +
	"\x10files_collection\x18\x02 \x01(\tR\x0ffilesCollection\x12/\n" +
	"\x13profiles_collection\x18\x03 \x01(\tR\x12profilesCollectionB>Z<github.com/tinywideclouds/gen-llm/go/types/cache/v1;cache_v1b\x06proto3"

var (
	file_src_types_cache_v1_cache_proto_rawDescOnce sync.Once
	file_src_types_cache_v1_cache_proto_rawDescData []byte
)

func file_src_types_cache_v1_cache_proto_rawDescGZIP() []byte {
	file_src_types_cache_v1_cache_proto_rawDescOnce.Do(func() {
		file_src_types_cache_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_types_cache_v1_cache_proto_rawDesc), len(file_src_types_cache_v1_cache_proto_rawDesc)))
	})
	return file_src_types_cache_v1_cache_proto_rawDescData
}

var file_src_types_cache_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_types_cache_v1_cache_proto_goTypes = []any{
	(*StoreCollectionsPb)(nil), // 0: src.types.cache.v1.StoreCollectionsPb
}
var file_src_types_cache_v1_cache_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_types_cache_v1_cache_proto_init() }
func file_src_types_cache_v1_cache_proto_init() {
	if File_src_types_cache_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_types_cache_v1_cache_proto_rawDesc), len(file_src_types_cache_v1_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_types_cache_v1_cache_proto_goTypes,
		DependencyIndexes: file_src_types_cache_v1_cache_proto_depIdxs,
		MessageInfos:      file_src_types_cache_v1_cache_proto_msgTypes,
	}.Build()
	File_src_types_cache_v1_cache_proto = out.File
	file_src_types_cache_v1_cache_proto_goTypes = nil
	file_src_types_cache_v1_cache_proto_depIdxs = nil
}
